apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "convertigo-chart.fullname" . }}
  namespace: curator
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - pwa.curator.atemkeng.eu
