apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: convertigo-site
  namespace: curator
spec:
  serviceName: c8o-front-site
  replicas: 1
  selector:
    matchLabels:
      app: convertigo-site
  template:
    metadata:
      labels:
        app: convertigo-site
      annotations:
        version: '1.0'
        hash: '123654988765'
    spec:
      containers:
        - name: convertigo-container-site
          image: convertigo/convertigo:latest-aks
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/workspace"
              name: c8o-workspace-volume-site
          ports:
            - containerPort: 28080
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_OPTS
              value: "
  -XX:+UseG1GC
  -Dconvertigo.engine.billing.enabled=true
  -Dconvertigo.engine.billing.persistence.jdbc.password=n188jF28H8OfTSj1rXwexbz7AuWK8F9pi1WGbx4ofjI=
  -Dconvertigo.engine.billing.persistence.jdbc.username=analytics
  -Dconvertigo.engine.billing.persistence.jdbc.url=jdbc:mysql://my-sql-mysql.default.svc.cluster.local:3306/c8oAnalytics
  -Dconvertigo.engine.billing.google.analytics.id=ga
  -Dconvertigo.engine.billing.google.enabled=true
  -Dconvertigo.engine.log4j.appender.CemsAppender.File=/workspace/logs/MY_POD_NAME/engine.log
  -Dconvertigo.engine.fullsync.couch.username=site
  -Dconvertigo.engine.fullsync.couch.password=site_couch_password
  -Dconvertigo.engine.fullsync.couch.url=http://cdb-fullsync-svc-couchdb:5984
  -Dconvertigo.engine.fullsync.couch.prefix=site_couch_prefix
  -Dconvertigo.engine.project.zip_backup_old=false
  -Dconvertigo.engine.delegate.url=https://c8ocloud.convertigo.net/convertigo/projects/C8oCloudKubernetes/.json?__sequence=Delegate\\&url=https://site.convertigo.net/convertigo/delegate
  -Dconvertigo.engine.admin.username=admin
  -Dconvertigo.engine.admin.password=adminpassword
  -Dconvertigo.cloud.customer_name=site
  -Djava.rmi.server.hostname=localhost
  -Dcom.sun.management.jmxremote.port=9010
  -Dcom.sun.management.jmxremote.rmi.port=9010
  -Dcom.sun.management.jmxremote.authenticate=false
  -Dcom.sun.management.jmxremote.ssl=false"
      volumes:
        - name: c8o-workspace-volume-site
          persistentVolumeClaim:
            claimName: c8o-volume-claim-site
---
apiVersion: v1
kind: Service
metadata:
  name: c8o-front-site
  namespace: curator
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
    - port: 80
      targetPort: 28080
  selector:
    app: convertigo-site
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: c8o-volume-claim-site
  namespace: curator
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "local-path"
  resources:
    requests:
      storage: 1Gi