superblocks:
  agentHostUrl: "http://admin.atemkeng.eu/"

#(...)

controller:
  service:
    # Use ClusterIP if your ingress controller routes traffic directly to pods.
    # Otherwise, update the type based on your ingress controller settings.
    # For example, defaults for native cloud controllers require NodePort.
    type: ClusterIP
    port: 8020



  ingress:
    enabled: true
    class: "" # nginx
    annotations: {}
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: admin.atemkeng.eu
        paths:
          - /
          - path: /agent
            pathType: Prefix
          - path: /health
    tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - YOUR.VALID.DOMAIN