apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
  labels:
    app: metallb
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metallb
    app.kubernetes.io/part-of: metallb
    helm.sh/chart: metallb 0.14.3
gateway:
  yaml:data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 5.199.139.35/32