{{- $fullName := .Values.app.name -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $fullName }}
  namespace: curator
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - core.curator.atemkeng.eu
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  namespace: curator
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  hosts:
    - core.curator.atemkeng.eu
  gateways:
    - {{ $fullName }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ $fullName }}
            port:
              number: 8899
{{/*    - match:*/}}
{{/*        - uri:*/}}
{{/*            prefix: /metrics*/}}
{{/*      route:*/}}
{{/*        - destination:*/}}
{{/*            host: {{ $fullName }}*/}}
{{/*            port:*/}}
{{/*              number: 9253*/}}

