annotations:
  artifacthub.io/changes: "- kind: added\n  description: \"add incressClassName definition
    to ingress PR#31 by swarnat\"\n  links:\n    - name: GitHub PR\n      url: https://github.com/8gears/n8n-helm-chart/pull/31\n-
    kind: added\n  description: \"Add lifecycle configuration for main deployment
    (#30) by tomaszkiewicz\"\n  links:\n    - name: GitHub PR\n      url: https://github.com/8gears/n8n-helm-chart/pull/30
    \   \n- kind: changed\n  description: \"Updated App Version to 0.210.0\"\n- kind:
    added\n  description: \"Support for dedicated Workers and Webhooks Instances by
    Stefan Warnat aka swarnat\"\n  links:\n    - name: GitHub PR\n      url: https://github.com/8gears/n8n-helm-chart/pull/24\n
    \   - name: \"Stefan Warnat aka @swarnat\"\n      url: https://github.com/swarnat\n"
apiVersion: v2
appVersion: 0.217.1
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.2.0
description: A Kubernetes Helm chart for n8n a free and open fair-code licensed node
  based Workflow Automation Tool. Easily automate tasks across different services.
home: https://github.com/8gears/n8n-helm-chart
icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
keywords:
- Workflow Automation
- Workflow
- iPaaS
- integration-framework
- low-code-plattform
- low-code
maintainers:
- name: Vadim Bauer
name: n8n
sources:
- https://github.com/n8n-io/n8n
- https://n8n.io/
type: application
version: 0.10.0
