apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobe-chat
  namespace: curator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lobe-chat
  template:
    metadata:
      labels:
        app: lobe-chat
    spec:
      containers:
        - name: lobe-chat
          image: lobehub/lobe-chat
          ports:
            - containerPort: 3210

---
apiVersion: v1
kind: Service
metadata:
  name: lobe-chat
  namespace: curator
spec:
  selector:
    app: lobe-chat
  ports:
    - protocol: TCP
      port: 3210
      targetPort: 3210

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: lobe-gateway
  namespace: curator
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "lobe.curator.atemkeng.eu"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lobe-virtualservice
  namespace: curator
spec:
  hosts:
    - "lobe.curator.atemkeng.eu"
  gateways:
    - lobe-gateway
  http:
    - route:
        - destination:
            host: lobe-chat
            port:
              number: 3210
