apiVersion: apps/v1
kind: Deployment
metadata:
  name: bentoml
  labels:
    app: bentoml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bentoml
  template:
    metadata:
      labels:
        app: bentoml
    spec:
      containers:
        - name: bentoml
          image: atemndobs/bentoml:v1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bentoml-service
spec:
  selector:
    app: bentoml
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bentoml-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "bentoml.curator.atemkeng.eu"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bentoml-virtualservice
spec:
  hosts:
    - "bentoml.curator.atemkeng.eu"
  gateways:
    - bentoml-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: bentoml-service
            port:
              number: 3333
