apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-scraper
  labels:
    app: amazon-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazon-scraper
  template:
    metadata:
      labels:
        app: amazon-scraper
    spec:
      containers:
        - name: amazon-scraper
          image: atemndobs/scraper:v0.3
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: amazon-scraper-service
spec:
  selector:
    app: amazon-scraper
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3000

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: amazon-scraper-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "scraper.curator.atemkeng.eu"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: amazon-scraper-virtualservice
spec:
  hosts:
    - "scraper.curator.atemkeng.eu"
  gateways:
    - amazon-scraper-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: amazon-scraper-service
            port:
              number: 3002
