apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "directus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "directus.fullname" . }}
    app.kubernetes.io/instance: {{ template "directus.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "directus.fullname" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ .Values.host }}
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "directus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "directus.fullname" . }}
    app.kubernetes.io/instance: {{ template "directus.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ template "directus.fullname" . }}
spec:
  gateways:
  - {{ template "directus.fullname" . }}
  hosts:
    - {{ .Values.host }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ template "directus.fullname" . }}
        port:
          number: 80