annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: app version to 1.14
apiVersion: v2
appVersion: 1.14.0
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.8.3
- condition: mongodb.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.31
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.17.3
description: MLOps platform
home: https://clear.ml
icon: https://raw.githubusercontent.com/allegroai/clearml/master/docs/clearml-logo.svg
keywords:
- clearml
- machine learning
- mlops
kubeVersion: '>= 1.21.0-0 < 1.29.0-0'
maintainers:
- name: valeriano-manassero
  url: https://github.com/valeriano-manassero
name: clearml
sources:
- https://github.com/allegroai/clearml-helm-charts
- https://github.com/allegroai/clearml
type: application
version: 7.6.0
