apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "curator-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: curator-app
    app.kubernetes.io/instance: curator-app
    helm.sh/chart: {{ include "curator-app.chart" . }}
    app: curator-app
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ .Values.host }}
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "curator-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: curator-app
    app.kubernetes.io/instance: curator-app
    helm.sh/chart: {{ include "curator-app.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: curator-app
spec:
  gateways:
  - curator-app
  hosts:
    - {{ .Values.host }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: curator-app
        port:
          number: 8080