apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ printf "%s-headless" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-headless" (include "common.names.fullname" .) }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    {{- $appProtocolAvailable := (semverCompare ">=1.20-0" (include "common.capabilities.kubeVersion" .)) }}
    - name: galera
      port: 4567
      targetPort: galera
      {{- if $appProtocolAvailable }}
      appProtocol: mysql
      {{- end }}
    - name: ist
      port: 4568
      targetPort: ist
      {{- if $appProtocolAvailable }}
      appProtocol: mysql
      {{- end }}
    - name: sst
      port: 4444
      targetPort: sst
      {{- if $appProtocolAvailable }}
      appProtocol: mysql
      {{- end }}
      hosts:
        - mariadb.curator.atemkeng.eu
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ printf "%s-headless" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-headless" (include "common.names.fullname" .) }}
spec:
  hosts:
    - mariadb.curator.atemkeng.eu
  gateways:
    - {{ printf "%s-headless" (include "common.names.fullname" .) }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ printf "%s-headless" (include "common.names.fullname" .) }}
            port:
              number: 3306

# db-mariadb-galera.curator.svc.cluster.local
