{{- $fullName := include "appsmith.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ include "appsmith.namespace" . }}
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/instance: {{ $fullName }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ $fullName }}
    app.kubernetes.io/part-of: {{ $fullName }}
    helm.sh/chart: {{ $fullName }}-2.0.7
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
    - host: curator.atemkeng.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
  tls:
    - hosts:
        - curator.atemkeng.eu
      secretName: appsmith-tls