nameOverride: admin

images:
  directus:
    repository: atemndobs/directus
    tag: v1.2
  #  tag: v9.0.0-rc.28

host: admin.curator.atemkeng.eu

config:
  clusterProvider: rke
  imagePullPolicy: Always
  updateStrategy: Recreate
  directus:
    baseUrl: ''
    hostname: ''
    resources:
      enabled: false
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  # adminEmail: 'admin@example.com'
  # adminPassword: 'P@ssw0rd'
  adminEmail: 'atemndobs@yahoo.com'
  adminPassword: 'Atem1234'
  postgres:
    integration:
    database: directus
    host: ''
    password: P@ssw0rd
    port: 5432
    url: ''
    username: postgres
  mysql:
#    integration:
    database: mage
    host: 'maxscale-masteronly.curator.svc.cluster.local'
    password: mage
    port: 3306
    url: ''
    username: mage

service:
  directus:
    type: ClusterIP
    externalTrafficPolicy: Cluster
    nodePorts:
      http:
    lbPorts:
      http: 80

ingress:
  directus:
    certificate: ''
    enabled: false
    hostname: ''
    tls: false
    issuer:
      name: letsencrypt-staging

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  storageClass: ''
  existingClaim:
    directus: ''
  size:
    directus: 1Gi
  velero:
    enabled: false
    restic: true
    schedule: '@midnight'
    ttl: 2160h0m00s

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
