apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "flowise.fullname" . }}-flowise-default
  labels:
  {{- include "flowise.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          io.kompose.network/flowise-default: "true"
  podSelector:
    matchLabels:
      io.kompose.network/flowise-default: "true"