apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8900
      targetPort: http
{{/*  type: ClusterIP*/}}
{{/*  ports:*/}}
{{/*    - port: {{ .Values.service.port }}*/}}
{{/*      targetPort: http*/}}
{{/*      protocol: TCP*/}}
{{/*      name: http*/}}
  selector:
    {{- include "laravel.selectorLabels" . | nindent 4 }}
    laravel.com/pod-type: web
