apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "maxscale.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "maxscale.name" . }}
    helm.sh/chart: {{ include "maxscale.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  maxscale.cnf: |-
    [maxscale]
    threads=auto
    skip_permission_checks=true
    admin_host=0.0.0.0
    # this enables external access to the REST API outside of localhost
    # please review / modify for any public / non development environments
    admin_port=8989
    admin_auth=1
    admin_enabled=1
    admin_secure_gui=false
    substitute_variables=true
    piddir=/var/cache/maxscale
    persistdir=/var/cache/maxscale
    datadir=/var/cache/maxscale
    # logdir=/var/log/maxscale
    log_info=true
    log_warn_super_user=true
    maxlog=true
    syslog=true

    [server-0]
    type=server
    address={{.Values.db1Address}}
    port=3306
    protocol=MariaDBBackend

    [server-1]
    type=server
    address={{.Values.db2Address}}
    port=3306
    protocol=MariaDBBackend

    [server-2]
    type=server
    address={{.Values.db3Address}}
    port=3306
    protocol=MariaDBBackend

    [MariaDB-Monitor]
    type=monitor
    module=galeramon
    servers=server-0,server-1,server-2
    backend_connect_timeout=3s
    backend_write_timeout=3s
    backend_read_timeout=3s
    disable_master_failback=false
    disable_master_role_setting=false
    user={{.Values.monitorUser}}
    password={{.Values.monitorPassword}}

    [Read-Write-Service]
    type=service
    router=readwritesplit
    master_failure_mode=fail_on_write
    servers=server-0,server-1,server-2
    user={{.Values.serviceUser}}
    password={{.Values.servicePassword}}
    enable_root_user=true

    [Read-Write-Listener]
    type=listener
    service=Read-Write-Service
    protocol=MariaDBClient
    port=3306
