apiVersion: v1
kind: Service
metadata:
  name: {{ include "maxscale.fullname" . }}-admin-ui
  labels:
    app.kubernetes.io/name: {{ include "maxscale.name" . }}
    helm.sh/chart: {{ include "maxscale.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: maxscale
  ports:
    - name: admin-ui
      port: 8989
      targetPort: 8989
  type: LoadBalancer