annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: '>=1.24'
apiVersion: v2
appVersion: 1.3.3
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami/
  version: 2.5.0
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami/
  version: 11.5.7
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami/
  version: 12.8.0
description: Drag & drop UI to build your customized LLM flow
home: https://flowiseai.com/
icon: https://avatars.githubusercontent.com/u/128289781
maintainers:
- email: sebastien.prudhomme@gmail.com
  name: sebastien-prudhomme
name: flowise
sources:
- https://github.com/FlowiseAI/Flowise
- https://github.com/cowboysysop/charts/tree/master/charts/flowise
version: 2.2.0
